version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    networks:
      - yii2-network

networks:
  yii2-network:
    driver: bridge